version: '3.8'

services:
  postgis:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: heirs_property
      POSTGRES_USER: heirs_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
      - ./logs/postgis:/var/log/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heirs_user -d heirs_property"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile.jupyter
    volumes:
      - .:/workspace
      - ./data:/data
      - ./notebooks:/workspace/notebooks
      - ./results:/workspace/results
      - ./logs/jupyter:/root/.local/share/jupyter/runtime
    ports:
      - "8888:8888"
    environment:
      - DATABASE_URL=postgresql://heirs_user:${POSTGRES_PASSWORD}@postgis:5432/heirs_property
      - PYTHONPATH=/workspace
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

  processing:
    build:
      context: .
      dockerfile: Dockerfile.processing
    volumes:
      - .:/workspace
      - ./data:/data
      - ./results:/workspace/results
      - ./logs/processing:/var/log/processing
    environment:
      - DATABASE_URL=postgresql://heirs_user:${POSTGRES_PASSWORD}@postgis:5432/heirs_property
      - PYTHONPATH=/workspace
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import sys; sys.exit(0)'"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgis:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

volumes:
  postgis_data:

networks:
  default:
    name: heirs_property_network 