[project]
name = "heirs-property"
version = "0.1.0"
description = "Analysis of heirs property parcels in North Carolina"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
dependencies = [
    "geopandas>=0.13.2",
    "pandas>=2.0.3",
    "numpy>=1.24.3",
    "rasterio>=1.3.8",
    "shapely>=2.0.1",
    "fiona>=1.9.4",
    "pyproj>=3.6.0",
    "matplotlib>=3.7.2",
    "dask>=2023.5.0",
    "dask-geopandas>=0.3.1",
    "rtree>=1.0.1",
    "pyarrow>=14.0.1",
    "fastparquet>=2023.8.0",
    "numba>=0.57.1",
    "scipy>=1.11.2",
]
requires-python = ">=3.9"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=7.4.0",
    "black>=23.7.0",
    "isort>=5.12.0",
    "mypy>=1.4.1",
    "ruff>=0.0.284",
]

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.ruff]
select = ["E", "F", "B"]
ignore = []
line-length = 88 