# Analysis pipeline configuration

# Input/output paths
input_dir: "data/raw"
output_dir: "data/processed"
ndvi_pattern: "ndvi_*.tif"

# Property matching configuration
matching:
  min_size_ratio: 0.6
  max_size_ratio: 1.4
  distance_threshold: 2000  # meters
  n_workers: null  # auto-detect

# Match validation configuration
validation:
  min_matches_per_heir: 1
  max_matches_per_heir: 5
  max_distance_outlier_std: 3.0
  max_area_ratio_outlier_std: 3.0

# NDVI processing configuration
ndvi:
  temporal_window: 5  # years
  save_intermediates: false
  chunk_size: 1000  # properties per chunk

# Statistical analysis configuration
stats:
  confidence_level: 0.95
  min_sample_size: 30
  methods:
    - t_test
    - mann_whitney 