project:
  name: Forest Biomass Analysis
  description: Forest biomass and diversity analysis
  version: 1.0.0
location:
  type: custom
  name: Great Smoky Mountains
  abbreviation: null
  fips_code: null
crs:
  source: EPSG:4326
  target: null
  web_mercator: EPSG:3857
bounding_boxes:
  wgs84:
    xmin: -84.0
    ymin: 35.4
    xmax: -83.0
    ymax: 36.0
  state_plane: null
  web_mercator:
    xmin: -9350837.226634981
    ymin: 4218373.2871734
    xmax: -9239517.735841706
    ymax: 4300621.372044271
species: []
zarr:
  output_path: output/data/forest_biomass.zarr
  chunk_size:
  - 1
  - 1000
  - 1000
  compression: lz4
  compression_level: 5
download:
  resolution_ft: 98.425197
  output_dir: output/data/species
  max_retries: 3
  timeout: 60
  rate_limit_delay: 0.5
visualization:
  biomass_cmap: YlGn
  diversity_cmap: plasma
  richness_cmap: Spectral_r
  boundary_color: black
  boundary_linewidth: 0.5
  figure_size:
  - 12
  - 10
  dpi: 150
analysis:
  presence_threshold: 1.0
  normalization_percentiles:
  - 2
  - 98
  nodata_value: -9999
paths:
  data_dir: output/data
  maps_dir: output/maps
  scripts_dir: scripts
  examples_dir: examples
