# BigMap Configuration for Total Biomass Analysis
# This configuration calculates total biomass as the sum of all species

# Application settings
app_name: "BigMap"
debug: false
verbose: true

# File paths
data_dir: "data"
output_dir: "output"
cache_dir: ".cache"

# Raster processing settings
raster:
  chunk_size: [1, 1000, 1000]  # (species, height, width)
  pixel_size: 30.0
  compression: "lz4"
  compression_level: 5

# Processing settings
processing:
  max_workers: null  # Auto-detect
  memory_limit_gb: 8.0
  temp_dir: null

# Visualization settings
visualization:
  default_dpi: 300
  default_figure_size: [16, 12]
  color_maps:
    biomass: "viridis"
    total_biomass: "plasma"
    diversity: "Spectral_r"
  font_size: 12

# Calculation configurations
calculations:
  - name: "total_biomass"
    enabled: true
    parameters: {}
    output_format: "geotiff"
    output_name: "nc_total_biomass"
  
  - name: "species_richness"
    enabled: true
    parameters:
      biomass_threshold: 1.0  # Minimum biomass to count as present
    output_format: "geotiff"
    output_name: "nc_species_richness"
    
  - name: "dominant_species"
    enabled: true
    parameters: {}
    output_format: "geotiff"
    output_name: "nc_dominant_species"