project:
  name: Forest Biomass Analysis
  description: Forest biomass and diversity analysis
  version: 1.0.0
location:
  type: state
  name: Texas
  abbreviation: null
  fips_code: null
crs:
  source: EPSG:4326
  target: EPSG:32139
  web_mercator: EPSG:3857
bounding_boxes:
  wgs84:
    xmin: -106.65
    ymin: 25.84
    xmax: -93.51
    ymax: 36.5
  state_plane: null
  web_mercator:
    xmin: -11872223.693102626
    ymin: 2979277.7157074944
    xmax: -10409485.584079012
    ymax: 4369640.51064983
species: []
zarr:
  output_path: output/data/forest_biomass.zarr
  chunk_size:
  - 1
  - 1000
  - 1000
  compression: lz4
  compression_level: 5
download:
  resolution_ft: 98.425197
  output_dir: output/data/species
  max_retries: 3
  timeout: 60
  rate_limit_delay: 0.5
visualization:
  biomass_cmap: YlGn
  diversity_cmap: plasma
  richness_cmap: Spectral_r
  boundary_color: black
  boundary_linewidth: 0.5
  figure_size:
  - 12
  - 10
  dpi: 150
analysis:
  presence_threshold: 1.0
  normalization_percentiles:
  - 2
  - 98
  nodata_value: -9999
paths:
  data_dir: output/data
  maps_dir: output/maps
  scripts_dir: scripts
  examples_dir: examples
