project:
  name: Forest Biomass Analysis
  description: Forest biomass and diversity analysis
  version: 1.0.0
location:
  type: county
  name: Los Angeles
  abbreviation: null
  fips_code: null
  state: California
crs:
  source: EPSG:4326
  target: EPSG:32610
  web_mercator: EPSG:3857
bounding_boxes:
  wgs84:
    xmin: -118.95
    ymin: 33.7
    xmax: -117.65
    ymax: 34.82
  state_plane: null
  web_mercator:
    xmin: -13241453.429859892
    ymin: 3988590.139019254
    xmax: -13096738.091828637
    ymax: 4139446.6880971724
species: []
zarr:
  output_path: output/data/forest_biomass.zarr
  chunk_size:
  - 1
  - 1000
  - 1000
  compression: lz4
  compression_level: 5
download:
  resolution_ft: 98.425197
  output_dir: output/data/species
  max_retries: 3
  timeout: 60
  rate_limit_delay: 0.5
visualization:
  biomass_cmap: YlGn
  diversity_cmap: plasma
  richness_cmap: Spectral_r
  boundary_color: black
  boundary_linewidth: 0.5
  figure_size:
  - 12
  - 10
  dpi: 150
analysis:
  presence_threshold: 1.0
  normalization_percentiles:
  - 2
  - 98
  nodata_value: -9999
paths:
  data_dir: output/data
  maps_dir: output/maps
  scripts_dir: scripts
  examples_dir: examples
